<?php
/**
 * Created by PhpStorm.
 * User: patrickkahnke
 * Date: 8/28/16
 * Time: 1:43 AM
 */

/**
 * @file
 * Contains proof_api.module
 */

/**
 * Implements hook_theme()
 * @return string
 */

function proof_api_theme($existing, $type, $theme, $path) {
    return array(
        'all_movies_page' => array(
            'variables' => 'title' => null,
            'url' => null,
            'slug' => null
        ),

    )
}